### ISSUE TITLE
This one stuck RUN npm install on AWS Amazon linux

### ISSUE THREAD

**Issue by kishorepasupuleti** [Sean-Bradley/Seans-TypeScript-NodeJS-CRUD-REST-API-Boilerplate#2]
Hi Bradley,

I installed gitlab runner on AWS Amazon linux and registered the runner. I ran the pipepine and it is getting stuck at RUN npm install step, not moving further. May I know what could be the reason
?

![image](https://user-images.githubusercontent.com/28624109/65143303-40174e80-da32-11e9-92f8-b22dcdce8f4c.png)

**Comment by Sean-Bradley** [comment]
Try with an ubuntu vm

**Comment by kishorepasupuleti** [comment]
Hey Bradley,

It worked with ubuntu instance on AWS . The job is successful and both ngnix/node containers are up and running. But when I do the localhost:8080 or localhost:3000 , I get connection refused. Should I change the network rules for this or any ports to be allowed on the host machine?


![image](https://user-images.githubusercontent.com/28624109/65211270-c1ff8a00-dabb-11e9-8b20-421c7121ac2d.png)

**Comment by Sean-Bradley** [comment]
try localhost:80

**Comment by kishorepasupuleti** [comment]
sorry , I was using 8080 port and it worked with 80 port. my last question is - I can't access outside of hosting machine. I am trying to access the web page using IPv4 public IP which is the machine public IP. should I need to change this to access the web page from outside?


![image](https://user-images.githubusercontent.com/28624109/65224101-22a0be00-dae0-11e9-9631-8d838f40d952.png)

**Comment by Sean-Bradley** [comment]
whats the public ip of your aws unbuntu

**Comment by kishorepasupuleti** [comment]
This is the public IP : 13.59.118.2

**Comment by kishorepasupuleti** [comment]
I also removed the firewall by running the command

firewall-cmd --zone=public --add-service=http

**Comment by Sean-Bradley** [comment]
is your the nginx docker container still running on 0.0.0.0:80

**Comment by Sean-Bradley** [comment]
also check your aws firewall rules, when you created the vm.
These problems you are having are AWS specific.

Watch these videos, you may find more clues in them

[![CI/CD with Gitlab Runner and Docker-Compose](https://img.youtube.com/vi/RV0845KmsNI/0.jpg)](https://youtu.be/RV0845KmsNI)

[![CI/CD a NodeJS API with Docker-Compose and GitLab](https://img.youtube.com/vi/Qlj6NiOy5jM/0.jpg)](https://youtu.be/Qlj6NiOy5jM)

**Comment by kishorepasupuleti** [comment]
Yes , the two containers are running. The ngnix container is running with port 0.0.0.0:80

![image](https://user-images.githubusercontent.com/28624109/65230456-8381c380-daeb-11e9-821e-bf8f070561e5.png)

**Comment by Sean-Bradley** [comment]
your port 22 is open, but not 80, check your firewall rules in aws

**Comment by Sean-Bradley** [comment]
what does 
```bash
curl localhost
```
do

**Comment by kishorepasupuleti** [comment]
Hey , I opened the port 80 and it worked. Can I deploy the same thing on redhat openshift?

Regards,
Kishore

**Comment by Sean-Bradley** [comment]
Excellent,
I can recommend a Red Hat OpenShift course for you, it uses Jenkins though.
<a href="https://click.linksynergy.com/deeplink?id=/BkCmHRznLg&mid=39197&murl=https%3A%2F%2Fwww.udemy.com%2Fcourse%2Fred-hat-openshift%2F" target="new">Red Hat OpenShift With Jenkins</a>
<img alt="icon" width="1" height="1" src="https://ad.linksynergy.com/fs-bin/show?id=/BkCmHRznLg&bids=507388.1&type=10">
