### ISSUE TITLE
A suggestion on Dockerlization

### ISSUE THREAD

**Issue by simivalley** [Sean-Bradley/Seans-TypeScript-NodeJS-CRUD-REST-API-Boilerplate#9]
Sean: 
  After watching your youtube video, I realized that docker-compose.yml was tailored to GitLab CI/CD.  Would that be a good idea to make a docker-compose.yml to deploy code on Windows 10 Docker Desktop with Nginx and Nodejs containers running?

Thank you for releasing your codes to the public. Learn a lot !

Simi Valley From California

**Comment by Sean-Bradley** [comment]
`docker-compose -f docker-compose.yml up -d`

is the way I use to do it on windows 4 years when I last looked at it
